backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets

collections:
  - name: "content" # used in routes, e.g. /admin/collections/blog
    label: "Page Content" # Used in the UI
    folder: "src/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{page-{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Is Draft?", name: "draft", widget: "string", default: "false"}
      - {label: "Title", name: "title", widget: "string"}